[package]
name = "tcp-listener"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.1"
log = "0.4.20"
signal-hook = "0.3.17"
tokio = { version = "1.35.1", features = ["full"] }
